language: python
python:
  - "2.7"
cache: pip

install:
  - 'pip install pipenv'
  - 'pipenv install'

script:
  # consider removing --disable-pytest-warnings at some point
  - pytest --disable-pytest-warnings --cov=webrob/..

after_success:
  - codecov

