language: python
python:
  - "2.7"
# command to install dependencies
cache: pip
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
# py.test --cov-report term-missing --cov app -v
branches:
  only:
    - master
