language: python
python:
  - "2.7"
cache: pip

install:
  - 'pip install pipenv'
  - 'pipenv install'

script:
  # run tests
  # consider removing --disable-pytest-warnings at some point
  - py.test --cov-report term --disable-pytest-warnings --cov=webrob/..

# TODO: consider adding codecov hook like demonstrated here: https://github.com/codecov/example-python
